#!/bin/bash

rootpath="/root/OneDrive/output"
time=$(date +'%Y-%m-%d-%H-%M')


usage(){
  echo " usage:
  default: run assertfinder for every domain under subdomain directory.
  ------------------
  optional argument -l: domain list to search undr apex directory, if null then search all domain
    " 1>&2;
  exit 1
}


while getopts  ":l:" option ;
do
    case $option in
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


subdomainpath=$rootpath/subdomain


assertfinder_dir(){
  echo

  dir=$1
  echo "debug: dir      $1"
  domain=$(basename $dir)

  echo "debug: domain      $domain"


  mkdir -p "$rootpath/assertfinder/$domain"


  assertfinder_output="$rootpath/assertfinder/${domain}/${time}_assertfinder_${domain}.txt"
  echo "debug:  assertfinder_output    $assertfinder_output"
  touch $assertfinder_output

  assertfinder --subs-only $domain > $assertfinder_output

}



if [[ -z ${domainlist+x} ]]; then
  for dir in $subdomainpath/* ; do
    echo "debug: domain = $dir "
    assertfinder_dir $dir
  done
else
  sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug: $subdomainpath/$p"
      assertfinder_dir "$subdomainpath/$p"
  done < "$domainlist"
fi
