#!/bin/bash

rootpath="/root/OneDrive/output"
time=$(date +'%Y-%m-%d-%H-%M')


usage(){
  echo " usage:
  default: run assetfinder for every domain under subdomain directory.
  ------------------
  optional argument -l: domain list to search undr apex directory, if null then search all domain
    " 1>&2;
  exit 1
}


while getopts  ":l:" option ;
do
    case $option in
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


subdomainpath=$rootpath/subdomain


assetfinder_dir(){
  echo

  dir=$1
  echo "debug: dir      $1"
  domain=$(basename $dir)

  echo "debug: domain      $domain"


  mkdir -p "$rootpath/assetfinder/$domain"


  assetfinder_output="$rootpath/assetfinder/${domain}/${time}_assetfinder_${domain}.txt"
  echo "debug:  assetfinder_output    $assetfinder_output"
  touch $assetfinder_output

  assetfinder --sub-only $domain > $assetfinder_output

}



if [[ -z ${domainlist+x} ]]; then
  for dir in $subdomainpath/* ; do
    echo "debug: domain = $dir "
    assetfinder_dir $dir
  done
else
  sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug: $subdomainpath/$p"
      assetfinder_dir "$subdomainpath/$p"
  done < "$domainlist"
fi
