#!/bin/bash

rootpath="/root/OneDrive/output"


input_dir="$rootpath/eyewitness/input"
output_dir="$rootpath/eyewitness/output"
mkdir $output_dir
time=$(date +'%Y-%m-%d-%H-%M')
mkdir $input_dir
input_path="$input_dir/${time}_mixed_eyewitness.txt"


usage(){
  echo " usage:
   -d  : path of apex directory where all domains live;
  -w :keyword which name targeted files  contain .
    " 1>&2;
  exit 1
}

while getopts  ":d:w:" option ;
do
    case $option in
        d) directory=$OPTARG
            ;;
        w) keyword=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


adding_url(){

  domainname=$1

  echo "debug:  Adding host to $input_path:   $domainname"
  echo $domainname >> $input_path

}

escape(){
   echo $1 | awk '{gsub(/\:\/\//,"_")}1'
}

check_line(){
  p=$1
  dir=$2
  newjpgname=$(escape $p).jpg
  for file in $rootpath/screenshot/$(basename $dir)/* ; do
    name=$(basename $file)
    if [[ $name == $newjpgname ]]; then
        echo "skipping already existed jpg $name"

        return
    fi
  done
   adding_url   $p
}


extract_dir(){

   dir=$1
   echo "debug: dir      $1"
   file=$(ls -t $1/*$keyword* | head -1 )
   echo "debug:  file    $file"

    cat $file| parallel -j0  check_line {} $dir

    echo
    echo
    echo
}



  for dir in $rootpath/$directory/* ; do
     extract_dir $dir
done
