#!/usr/bin/env bash
ffuf_Wordlist=/root/Wordlist/endpoint/10w_common.txt
iprange="173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 104.16.0.0/12 172.64.0.0/13 131.0.72.0/22"


usage() { echo -e "Usage: $0 -f input file, -o outputdir " 1>&2; exit 1; }

while getopts ":f:o:" o; do
    case "${o}" in
      f) input=$OPTARG
        ;;
      o) outputdir=$OPTARG
          ;;
      *) usage
        exit 1
          ;;
    esac
done
shift $((OPTIND - 1))

export outputdir
export ffuf_Wordlist
export iprange

[ ! -d "$outputdir" ] && echo "Directory "$outputdir" DOES NOT exists." && exit


mkdir -p $ouputdir/raw
mkdir -p $ouputdir/processed
touch $outputdir/ffuf_output.html


ffuf_one(){
    _domain=$(echo $1 | unfurl -unique domain )
    ip=$(dig +short ${_domain}  @8.8.8.8 | tail -n 1)
    if [[ ! $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
       echo "Dns look up for $1 has some problem " >> $outputdir/ffuf_output.html
       return
    fi
    echo "$ip" | grepcidr "$iprange" > /dev/null && echo "<h3>$1 ----   $ip is in cloudfare</h3>" >> $outputdir/ffuf_output.html && return
    echo "ffufing $1 "
    ffuf -w $ffuf_Wordlist   -u $1/FUZZ -se -r -sf -fs 0 -fw 1  -o $outputdir/raw/${_domain} -of csv
    python3 /root/recon_tools/Scripts/python/ffuf_process.py $outputdir/raw/${_domain}  $outputdir/processed/"${_domain}_processed"
}


export -f ffuf_one

cat << 'EOF' > $outputdir/ffuf_output.html
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1.0"
    />
    <title>FFUF Report - </title>
    <!-- CSS  -->
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
	/>
	<link
	  rel="stylesheet"
	  type="text/css"
	  href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css"
	/>

  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">FFUF</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        </ul>
      </div>
    </nav>
    <main class="section no-pad-bot" id="index-banner">
      <div class="container">
        <br /><br />
        <h1 class="header center ">FFUF Report</h1>
        <div class="row center">
EOF

  cat $input | parallel -j2 ffuf_one {}

cat << 'EOF' >  $outputdir/ffuf_output.html
</div>
<br /><br />
</div>
</main>
<!--JavaScript at end of body for optimized loading-->
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
<script>
$(document).ready( function () {
$('#ffufreport').DataTable();
} );
</script>
<style>
body {
display: flex;
min-height: 100vh;
flex-direction: column;
}
main {
flex: 1 0 auto;
}
</style>
</body>
</html>
EOF
