#!/bin/bash
rootpath="/root/OneDrive/output"

usage(){
  echo " usage:
   -d  : path of apex directory where all domains live;
  -w :keyword which name targeted files  contain .
  ------------------
  optional argument -l: domain list to search undr apex directory, if null then search all domain
    " 1>&2;
  exit 1
}

httprobe_dir(){
    dir=$1
    echo "debug: dir      $1"
    mkdir -p "$rootpath/httprobe/$(basename $dir)"
    fileinput=$(ls -t $dir/*$keyword* | head -1 )
    echo "debug:  fileinput    $fileinput"

    if [[ ! -s $fileinput ]]; then
      return
    fi

    newfile="$rootpath/httprobe/$(basename $dir)/httprobe_$(basename $fileinput)"
    echo "debug:  newfile    $newfile"
    touch $newfile
    cat $fileinput| httprobe -c 50  >> $newfile

    echo
    echo
    echo
    echo
}

while getopts  ":d:w:l:" option ;
do
    case $option in
        d) directory=$OPTARG
            ;;
        w) keyword=$OPTARG
            ;;
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


if [[ -z ${domainlist+x} ]]; then
  for dir in $rootpath/$directory/* ; do
    echo "debug: domain = $dir "
    httprobe_dir $dir
  done
else
  sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug: $rootpath/$directory/$p"
      httprobe_dir "$rootpath/$directory/$p"
  done < "$domainlist"
fi
