#!/bin/bash
rootpath="/root/OneDrive/output"

usage(){
    echo " usage: -d  specify target direcotries  -s target file containing specific string for httprobe to check  " 1>&2;
    exit 1
}

httprobe_dir(){
    echo
    echo

    $dir=$1
    echo "debug: dir      $1"
    mkdir -p "$rootpath/httprobe/$(basename $dir)"
    fileinput=$(ls -t $dir/*$keyword* | head -1 )
    echo "debug:  fileinput    $fileinput"
    newfile="$rootpath/httprobe/$(basename $dir)/httprobe_$(basename $fileinput)"
    echo "debug:  newfile    $newfile"
    touch $newfile
    cat $fileinput| httprobe -c 50  >> $newfile

}

while getopts  ":d:w:l:" option ;
do
    case $option in
        d) directory=$OPTARG
            ;;
        w) keyword=$OPTARG
            ;;
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


if [[ -z ${domainlist+x} ]]; then
  for dir in $rootpath/$directory/* ; do
    echo "debug: domain = $dir "
    httprobe_dir $dir
  done
else
  sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug: $rootpath/$directory/$p"
      httprobe_dir "$rootpath/$directory/$p"
  done < "$domainlist"
fi
