#!/bin/bash

httprobepath="/root/OneDrive/output/httprobe"

processing_subdomain="/root/OneDrive/output/processing_sub"

mkdir -p $processing_sub

host2domain(){
  echo $1 | awk -F[/:] '{print $4}'

}

processing(){
  echo "processing file $1"
  while read p ; do
      newfilename=processed_$(basename $p)
      newfilepath=$processing_subdomain/$newfilename
      host2domain $p > $newfilepath
  done < $1
}

for dir in $httprobepath/* ; do
   echo "debug: dir   $dir"
   for file in $dir/* ; do
      processing $file
  done
done

for dir in $processing_subdomain/* ; do
   echo "debug: deduplicating.....  domain  $dir"
   for file in $dir/* ; do
      remove_dup $file
  done
done
