#!/bin/bash

httprobepath="/root/OneDrive/output/httprobe"

processing_subdomain="/root/OneDrive/output/processing_sub"

mkdir -p $processing_subdomain

host2domain(){
  echo $1 | awk -F[/:] '{print $4}'

}

processing_dir(){
  dir=$1
  domain=$(basename $dir)
  for file in $dir/* ; do
  echo "processing file $file"
    while read p ; do
        newfilename=processed_$(basename $p)
        newfilepath=$processing_subdomain/$domain/$newfilename
        host2domain $p > $newfilepath
    done < $file
  done
}

for dir in $httprobepath/* ; do
   echo "debug: dir   $dir"
   processing_dir $dir
done

for dir in $processing_subdomain/* ; do
   echo "debug: de duplicating.....  domain  $dir"
   for file in $dir/* ; do
      remove_dup $file
  done
done
