#!/bin/bash
rootpath="/root/OneDrive/output"
massdns_full_path="/tmp/massdnsfull"


usage(){
    echo "usage:
    -w  path of wordlist;
    -t  type of output : S - simple, F - full, other - json,
    debug

    fuckyou
     -d domain " 1>&2;
    exit 1
}

type=S

while getopts  ":w:t:d:" option ;
do
    case $option in
        w)  wordlist=$OPTARG
            ;;
        d) domain=$OPTARG
            ;;
        t) type=$OPTARG
            ;;
        *)usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if [[ ! $type =~ ^(S|F|J)$  ]]; then
    usage
fi


time=$(date +'%Y-%m-%d-%H-%M')
textname="${time}_massdns"

echo $textname


if [[  $type == "S"  ]]; then
    textname="${textname}_simple.txt"
elif [[  $type == "F"  ]]; then
    textname="${textname}_full.txt"
else
    textname="${textname}_json.txt"
fi


echo $output_file

if [[ $type == "F" ]]; then
  mkdir -p $massdns_full_path/$domain/
  touch  $massdns_full_path/$domain/$textname
  output_file=$massdns_full_path/$domain/${textname}

  subbrute.py $wordlist $domain |massdns -r ~/Wordlist/resolver.txt -t A -o $type --outfile  $output_file
else
  mkdir -p $rootpath/massdns/$domain/
  touch  $rootpath/massdns/$domain/$textname
  output_file=$rootpath/massdns/$domain/${textname}

  subbrute.py $wordlist $domain |massdns -r ~/Wordlist/resolver.txt -t A -o $type --outfile  $output_file
fi
