#!/bin/bash

concurrency_threads=1000
rootpath="/root/OneDrive/output"
time=$(date +'%Y-%m-%d-%H-%M')
textname="${time}_meg_mixed_input.txt"
# wordlist="/root/Wordlist/endpoint/meg.txt"

mkdir -p $rootpath/meg/input
touch "$rootpath/meg/input/$textname"
file_mixed_path="$rootpath/meg/input/$textname"
output_dir="$rootpath/meg/output/${time}_mixed"

mkdir -p $output_dir


usage(){
  echo " usage:
   -d  : path of apex directory where all domains live;
  -w :wordlist .
  -k :keyword which name targeted files  contain .
  ------------------
  optional argument -l: domain list to search undr apex directory, if null then search all domain
    " 1>&2;
  exit 1
}

while getopts  ":d:w:k:l:" option ;
do
    case $option in
        d) directory=$OPTARG
            ;;
        w) wordlist=$OPTARG
            ;;
        k) keyword=$OPTARG
            ;;
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


append(){
    dir=$1
    echo "debug: dir      $1"
    file_to_append=$(ls -t $dir/*$keyword* | head -1 )
    if [[ ! -s $file_to_append ]]; then
      return
    fi
    echo "debug:  file_to_append    $file_to_append"

    cat $file_to_append >> $file_mixed_path

}

run_meg(){
  meg -c $concurrency_threads $wordlist $file_mixed_path $output_dir | tee $output_dir/error.log 2>&1
}

remove_unnecessary_dir(){
  while sleep 600; do
    find $output_dir -mindepth 1 -maxdepth 1 -type d -print0 | xargs -0 rm -R
    echo
    echo "Clear the dirs under $output_dir"
    echo
  done
}

run(){
  trap 'kill %1' SIGINT
  remove_unnecessary_dir &
  run_meg
  wait
}



if [[ -z ${domainlist+x} ]]; then
for dir in $rootpath/$directory/* ; do
      echo "debug: dir  $dir"
      append $dir
done

run

else

sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug: dir    $rootpath/$directory/$p"
      append $rootpath/$directory/$p
  done < "$domainlist"

run
fi
