#!/bin/bash

concurrency_threads=800
rootpath="/root/OneDrive/output"
time=$(date +'%Y-%m-%d-%H-%M')
textname="${time}_meg_mixed_input.txt"
wordlist="/root/Wordlist/endpoint/meg.txt"

mkdir -p $rootpath/meg/input
touch "$rootpath/meg/input/$textname"
file_mixed_path="$rootpath/meg/input/$textname"
output_dir="$rootpath/meg/output/${time}_mixed"

mkdir -p $output_dir


usage(){
  echo " usage:
   -d  : path of apex directory where all domains live;
  -w :keyword which name targeted files  contain .
  ------------------
  optional argument -l: domain list to search undr apex directory, if null then search all domain
    " 1>&2;
  exit 1
}

while getopts  ":d:w:l:" option ;
do
    case $option in
        d) directory=$OPTARG
            ;;
        w) keyword=$OPTARG
            ;;
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


append(){
    dir=$1
    echo "debug: dir      $1"
    file_to_append=$(ls -t $dir/*$keyword* | head -1 )
    if [[ ! -s $file_to_append ]]; then
      return
    fi
    echo "debug:  file_to_append    $file_to_append"

    cat $file_to_append >> $file_mixed_path

}

run_meg(){
  meg -c $concurrency_threads $wordlist $file_mixed_path $output_dir
}

if [[ -z ${domainlist+x} ]]; then
for dir in $rootpath/$directory/* ; do
      echo "debug: dir  $dir"
      append $dir
done
run_meg
else
  sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug: dir    $rootpath/$directory/$p"
      append $rootpath/$directory/$p
  done < "$domainlist"
  run_meg
fi
