#!/bin/bash
rootpath="/root/OneDrive/output"

usage(){
  echo " usage:
   -d  : path of apex directory where all domains live;
  -w :keyword which name targeted files  contain .
  ------------------
  optional argument -l: domain list to search undr apex directory, if null then search all domain
    " 1>&2;
  exit 1
}


while getopts  ":d:w:l:" option ;
do
    case $option in
        d) directory=$OPTARG
            ;;
        w) keyword=$OPTARG
            ;;
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))

mkdir -p /root/OneDrive/photo_www/jpgs
photo_path="/root/OneDrive/photo_www/jpgs"

copy_photo_dir(){
  dir=$1
  last=-1; find $dir -type f -name '*.png' -printf '%f\0' | sort -nz |
    while read -d '' i; do
        s=$(stat -c '%s' "$i");
        [[ $s = $last ]] || mv "$i" $photo_path;
    last=$s;
done
}


if [[ -z ${domainlist+x} ]]; then
  for dir in $rootpath/$directory/* ; do
    echo "debug: dir  = $dir "
    copy_photo_dir $dir
  done
else
  sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug:dir  $rootpath/$directory/$p"
      copy_photo_dir "$rootpath/$directory/$p"
  done < "$domainlist"
fi
