#!/bin/bash

rootpath="/root/OneDrive/output/masscan"
outputpath="$rootpath/output/$time"

time=$(date +'%Y-%m-%d-%H-%M')
mkdir -p $outputpath/$time

usage(){
  echo " usage:
   -d  : file name  ;
    " 1>&2;
  exit 1
}

while getopts  ":d:" option ;
do
    case $option in
        d) inputfile=$OPTARG
            ;;

        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))

outfile=$outputpath/nmap.out
touch $outfile


nmap_one(){

  nmap -sV -T3 -p$2   -g 60000 --version-intensity 8 $1 >> $outfile
}

export -f nmap_one
export outfile

parallel -j10 --colsep ' ' nmap_one {1} {2}  :::: $inputfile
