#!/usr/bin/env python3

import sys

recordfile = sys.argv[1]
originalfile = sys.argv[2]
outputfilename = "output_"+originalfile


lines_to_save = set()


with open(recordfile, "r",encoding='utf-8') as f:
    for line in f.readlines():
        lines_to_save.add(line)


line_to_write=[]

with open(originalfile, "r",encoding='utf-8') as f:
     for line in f.readlines():
            print(line)
        if  any(s in line for s in lines_to_save):
            line_to_write.append(line)
            print(line)


with open(outputfilename,'w',encoding='utf-8') as w:
    w.write('\n'.join(line_to_write))
