#!/usr/bin/python3

import sys
import traceback


filename = sys.argv[1]

dns_dict = dict()

count = 1000

try:
    with open(filename,encoding='utf-8') as input:
        for row in input:
            domain, recordtype, resource = row.split()
            if resource in dns_dict:
                if len(dns_dict[resource[0]])> count:
                    continue
                dns_dict[resource[0]].append(domain)
            else:
                dns_dict[resource] = [[domain], recordtype]
except Exception as  e :
    print(traceback.format_exc())

for k,list in dns_dict.items():
    for row in list[0]:
            print(' '.join(map(str,[row,list[1],k])))
