#!/bin/bash

rootpath="/root/OneDrive/output"

usage(){
  echo " usage:
   -d  : path of apex directory where all domains live;
  -w :keyword which name targeted files  contain .
  ------------------
  optional argument -l: domain list to search undr apex directory, if null then search all domain
    " 1>&2;
  exit 1
}

rm_false_dir(){
  echo

  dir=$1
  echo "debug: dir      $1"
  mkdir -p "$rootpath/rmed_false/$(basename $dir)"
  file=$(ls -t $1/*$keyword* | head -1 )
  echo "debug:  file    $file"
  newfile=$rootpath/rmed_false/$(basename $dir)/rm_$(basename $file)
  echo "debug:  newfile    $newfile"
  rm_false_positive_massdns_one $file > $newfile
}


while getopts  ":d:w:l:" option ;
do
    case $option in
        d) directory=$OPTARG
            ;;
        w) keyword=$OPTARG
            ;;
        l) domainlist=$OPTARG
            ;;
        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))


if [[ -z ${domainlist+x} ]]; then
  for dir in $rootpath/$directory/* ; do
     echo "debug: dir  $dir"
     rm_false_dir $dir
done
else
  sed 's/[[:blank:]]*$//' $domainlist
  while read p ; do
      echo "debug: dir    $rootpath/$directory/$p"
      rm_false_dir "$rootpath/$directory/$p"
  done < "$domainlist"
fi
