#!/bin/bash

processing(){
  cd /tmp
  python3 ~/recon_tools/Scripts/python/random_domain.py

  massdns -r /root/Wordlist/resolver.txt Generated_domain.txt.1  -t A -o F -w  /tmp/test.massdns

  grep -B 3 --no-group-separator -i -E "noerror|refused|servfail"  test.massdns| sed -n 1~4p| awk -F: '{print $2}'| awk '{$1=$1}1' | awk '!seen[$0]++' > bad_resolvers.txt

  comm -2 -3 <(sort /root/Wordlist/resolver.txt) <(sort /tmp/bad_resolvers.txt) > /tmp/resolver.txt
  mv /tmp/resolver.txt /root/Wordlist/resolver.txt
}

previous=dummy
after=ymmuy
pwd=$(pwd)
index=0

before=$(wc -l /root/Wordlist/resolver.txt| awk '{print $1}')



while [[ $index -le 10 ]]; do
  if [[ $previous -eq $after ]]; then
    index=$index+1
  fi
  previous=$(wc -l /root/Wordlist/resolver.txt| awk '{print $1}')
  echo "before $previous"
  processing
  after=$(wc -l /root/Wordlist/resolver.txt|  awk '{print $1}')
  echo "after $after"

done

cd $pwd


echo "Finished!!!
      before: $before
      now: $after
"
