#!/bin/bash

apiKey="589fc98f-0175-409d-be59-54a3a712bd33"
apiSecret="eCPrjpwIC2rmY3EwqE2a3n7jR7xAlpQaNZQ8y9EhCOnQfjEgpE"
queryString="$1"
token=`printf '%s' "$queryString" | openssl sha1 -hmac "$apiSecret" | sed 's/^.* //'`

echo "https://api.screenshots.cloud/v1/screenshot/$apiKey/$token?$queryString"
