#!/bin/bash

apiKey="b46019e0-c21e-41de-bb11-3a7f350ab7b9"
apiSecret="XzJW37zbAtbkBFqnyW3JFo2LMWhLWMCjD8A0B4Y9eWVM7sllNQ"
queryString="$1"
token=`printf '%s' "$queryString" | openssl sha1 -hmac "$apiSecret" | sed 's/^.* //'`

echo "https://api.screenshots.cloud/v1/screenshot/$apiKey/$token?$queryString"
