#!/bin/bash

rootpath="/root/OneDrive/output/massdnsfull"

usage(){
  echo " usage:
   -d  : domain name  ;
    " 1>&2;
  exit 1
}


while getopts  ":d:" option ;
do
    case $option in
        d) domain=$OPTARG
            ;;

        *) usage
          exit 1
            ;;
    esac
done
shift $((OPTIND-1))

time=$(date +'%Y-%m-%d-%H-%M')
domainpath=$rootpath/$domain

massdns_output_path="$domainpath/second_result/${time}_massdns_second_full.txt"

tmp_SR_file="/tmp/$time_SR_$domain.txt"

dig_result_resolvers_name="$time_$domain_resolvers.txt"
dig_result_resolvers_path=$domainpath/resolvers/$dig_result_resolvers_name

valid_SR_file_name=$time_SR_$domain_valid.txt
valid_SR_file_path=$domainpath/valid_SR_subdomain/$valid_SR_file_name



sed_domain_record(){
  sed -n '/REFUSED/{n; n; n; n ; p}' $1 | awk '{print $1}' > $2
  sed -n '/SERVFAIL/{n; n; n; n ; p}' $1 | awk '{print $1}' > $2
}

dig_domain_file(){
  while read p; do
    echo "debug:  dig $p"
    answer=$(dig $p +short ns)
     echo $answer>> $2
     if [[ ! -z $answer ]]; then
       echo $p >> $3
     fi
done < "$1"
}


main(){
file=$(ls -t $domainpath/*full* | head -1 )
sed_domain_record $file $tmp_SR_file
mkdir -p $domainpath/resolvers
touch $dig_result_resolvers_path

dig_domain_file $tmp_SR_file  $dig_result_resolvers_path   $valid_SR_file_path

mkdir -p $domainpath/second_result/

massdns -r $dig_result_resolvers_path -t A -o F $valid_SR_file_path --outfile $massdns_output_path
}

main
