#!/bin/bash

rootpath="/tmp/test"

query="&format=jpg&timeout=10000"


directory=hosts
keyword=merge

screenshot(){


  domainname=$1
  jpgfile=$2

  echo "debug:  starting to screenshot domain_name:   $domainname"
  echo "debug: will generate new jpg_file: $jpgfile"

  requestedurl=$(screenshotcloud  "url=$domainname$query")
  echo "debug:  Requested url   $requestedurl"
  curl -m 60 $requestedurl > $jpgfile

  echo
  echo
    echo
}

escape(){
   echo $1 | awk '{gsub(/\:\/\//,"_")}1'
}



screenshot_line(){
  p=$1
  dir=$2
  newjpgname=$(escape $p).jpg
  for file in $rootpath/screenshot/$(basename $dir)/* ; do
    name=$(basename $file)
    if [[ $name == $newjpgname ]]; then
      echo "skipping already existed jpg $name"

        return
    fi
  done

   screenshot   $p  "$rootpath/screenshot/$(basename $dir)/$newjpgname"
}

export -f screenshot_line
export -f screenshot
export -f escape
export rootpath

screenshotdir(){

   dir=$1
   mkdir -p "$rootpath/screenshot/$(basename $dir)"
   file=$(ls -t $1/*$keyword* | head -1 )
   echo "debug:  host file:    $file"

    cat $file| parallel -j0  screenshot_line {} $dir

   # while read p ; do
   #    newjpgname=$(escape $p).jpg
   #    for file in rootpath/screenshot/$(basename $dir)/* ; do
   #      name=$(basename $file)
   #      if [[ $name == $newjpgname ]]; then
   #          continue 2
   #      fi
   #    done
   #     screenshot   $p  "$rootpath/screenshot/$(basename $dir)/$newjpgname"
   #  done < "$file"

    echo
}


for dir in $rootpath/$directory/* ; do
   echo "debug: dir  $dir"
   screenshotdir $dir
done
